### PR TITLE
Basic Tcl eval support

### PR DESCRIPTION
**Pull request by rkeene**
Basic Tcl eval support to support [dbohdan/tcl-duktape#5]

### CODE REVIEW

**Comment by rkeene** [comment]
Instead of binding the Tcl interpreter to the Duktape context using the `udata`, maybe it is better to use a hidden symbol

**Comment by dbohdan** [comment]
Nice!  This takes care of the biggest missing piece in tcl-duktape's API.  It seems to work right and the code looks reasonable to me.

There are two changes I want to request before I merge this PR.

1. This feature makes running JavaScript code from Tcl more dangerous than it has been up to this point.  Right now if you run JavaScript code in an unsafe interp it can't access your filesystem.  I think that's the right default.  Could you make it so that the user has to explicitly enable this feature with a command?  E.g., you could refactor the code that creates `Duktape.tcl.eval` into a command.
2. Please add a test.

**Comment by dbohdan** [comment]
A hidden symbol would feel cleaner and "less global" than `heap_udata`, but I am okay with either approach. It can be changed later.

**Comment by rkeene** [comment]
It now requires that you initialize it with `[::duktape::init -tcl]` -- I missed the part of comment about it being a separate command, maybe that's better overall

**Comment by dbohdan** [comment]
:+1: A flag is fine.

**Comment by rkeene** [comment]
Now there's `[::duktape::makesafe <token>]`, `[::duktape::makeunsafe <token>]`, and the flag has been renamed to `-unsafe` and accepts a boolean:

example:
```tcl
set token [::duktape::init -unsafe false]
::duktape::makeunsafe $token
::duktape::eval $token {
        console = {
                log: function(message) {
                        Duktape.tcl.eval('puts', message);
                }
        };
        console.log('Hello World!');
}
::duktape::makesafe $token
::duktape::eval $token {
        console.log('No more world');
}
```


Output:
```text
Hello World!
TypeError: cannot read property 'eval' of undefined
    while executing
"::duktape::eval $token {
        console.log('No more world');
}"
    (file "./eval-test.tcl" line 18)
```

However, since ::duktape::tclfunction is implemented by calling Duktape.tcl.eval() rather than registering a function, any new functions you register will similarly fail to work -- maybe registered functions should always work, even if not unsafe ?

**Comment by rkeene** [comment]
Now `[::duktape::tclfunction]` is handled in C and registers a function which can be called regardless of whether or not Tcl-eval is enabled.

There's still some question about how to properly coerce the types into Tcl as noted here:

https://github.com/rkeene/tcl-duktape/blob/5c9f111ff80221a607231eab7dbae04d830a90bc/lib/tcl-duktape.c#L140-L146

How it's done right now is mostly just convert objects to JSON, null/undefined to an empty string, and everything else is converted to a string.

**Comment by rkeene** [comment]
Small example:

```text
rkeene@railroad:~/devel/tcl-duktape/build/work$ cat -n eval-test.tcl
     1  #! /usr/bin/env tclsh
     2
     3  lappend auto_path .
     4  package require duktape
     5
     6  set token [::duktape::init]
     7
     8  ::duktape::tclfunction $token __puts {args} {
     9          puts {*}$args
    10  }
    11
    12  ::duktape::eval $token {
    13          runtime = {};
    14          runtime.puts = __puts;
    15          delete __puts;
    16
    17          console = {};
    18          console._formatArgs = function(argInfo) {
    19                  var idx, outArray;
    20                  var arg;
    21
    22                  idx = 0;
    23                  outArray = [];
    24                  for (idx = 0; idx < argInfo.length; idx++) {
    25                          arg = argInfo[idx];
    26                          if (typeof(arg) === 'string' || typeof(arg) === 'number') {
    27                                  outArray.push(arg);
    28                          } else {
    29                                  outArray.push(JSON.stringify(arg));
    30                          }
    31                  }
    32                  return(outArray.join(' '));
    33          }
    34          console.log = function() {
    35                  runtime.puts("CON> " + console._formatArgs(arguments));
    36          }
    37          console.error = function(message) {
    38                  runtime.puts("stderr", "ERR> " + console._formatArgs(arguments));
    39                  return;
    40          }
    41          console.debug = function(message) {
    42                  runtime.puts("DBG> " + console._formatArgs(arguments));
    43                  return;
    44          }
    45
    46          foo = {
    47                  bar: "baz",
    48                  arr: [1,2,3]
    49          }
    50
    51          console.log("Hello World! Foo=", foo);
    52          console.debug("Debug World!");
    53  }
rkeene@railroad:~/devel/tcl-duktape/build/work$ ./eval-test.tcl
CON> Hello World! Foo= {"bar":"baz","arr":[1,2,3]}
DBG> Debug World!
rkeene@railroad:~/devel/tcl-duktape/build/work$
```

**Comment by dbohdan** [comment]
:+1: to `make(un)safe` and especially the new safe `tclfunction`.  Those are nice enhancements.

I think `-unsafe` is more descriptive than `-tcl`.  Since the flag accepts a boolean, I've renamed it further to `-safe`.  Then you can avoid the double negative of `-unsafe false`.  I've also edited the commit messages and renamed the commands (adding dashes) to match the house style.  Take a look at my changes at https://github.com/dbohdan/tcl-duktape/tree/rkeene-tcl-eval.  If you have no objections to them I will be merging that branch to master.

**Comment by rkeene** [comment]
I'm still working on how objects will get passed back and forth between JavaScript and Tcl, handling formatting and encoding.  Last night I added (but didn't commit/push) primitive buffer support:

```diff
--- a/lib/tcl-duktape.c
+++ b/lib/tcl-duktape.c
@@ -150,6 +150,10 @@ static duk_ret_t EvalTclFromJSWithInterp(Tcl_Interp *interp, duk_context *ctx) {
                        dukStringLength = 0;
                }
 
+               if (duk_is_buffer_data(ctx, idx)) {
+                       duk_buffer_to_string(ctx, idx);
+               }
+
                if (duk_check_type(ctx, idx, DUK_TYPE_OBJECT)) {
                        duk_json_encode(ctx, idx);
                }
```

But there's  more work before it should be merged to make the interface between the two type systems useful

**Comment by dbohdan** [comment]
All right.  You can merge my branch `rkeene-tcl-eval` and continue working on top of it.

**Comment by rkeene** [comment]
I think the last architectural piece missing is that tclfunctions should declare a return type so that they may be ingested by JavaScript:

`::duktape::tcl-function <token> <name> <retType> <args> <body>`

Sound good ?

Also, shouldn't "`::duktape::jsproc`" be "`::duktape::js-proc`" to be compatible with the naming scheme ?  It's why I named "`tclfunction`" that way because it is the counterpart to "`jsproc`".

**Comment by rkeene** [comment]
Updated to support an optional `returnType` parameter to `::duktape::tcl-function`

I think the last remaining issue is handling encoding differences between the two sides.

**Comment by dbohdan** [comment]
It makes sense to declare the return type.  Not sure whether `<retType> <args> <body>` or `<args> <retType> <body>` reads better and fits better with the syntax of existing commands like `call token function ?{arg ?type?}?`.  Comparing
```
::duktape::tcl-function $token frobnicate int {x y} {
    # ...
}
```
and
```
::duktape::tcl-function $token frobnicate {x y} int {
    # ...
}
```
I somewhat prefer the latter, but I'll leave it up to you to choose.

I see what you mean with `::duktape::jsproc`.  It probably _should_ have been called `js-proc`.  However, at the time I named it after Critcl's `cproc`.  It's isn't too late to make it consistent.  Would you be in favor of renaming `jsproc` and `jsmethod` to `js-proc` and `js-method`?

**Comment by rkeene** [comment]
The reason I put the return type after the name is because that way the last two arguments together make up a list that we can directly hand off to `[apply]` as its first argument

**Comment by rkeene** [comment]
I checked and the encoding pushed by strings is UTF-8 already (CESU-8 really... but close enough since Tcl does not currently support things above the BMP) so there is no encoding work.

I added support for converting from JavaScript arrays to Tcl lists, and I think that's everything.

Let me know what you think.

Thanks !

**Comment by rkeene** [comment]
I have also started on support for converting JavaScript function objects into Tcl lambdas, but there is some more work to go for that and it's probably out of scope for this changeset.

Example:

```text
js> f = function(x) { console.log("x =", x); }
function () { [ecmascript code] }
js> Duktape.tcl.eval('apply', f, "Test")
=> x = Test
js>
```

It's pretty fast too:
```text
js> Duktape.tcl.eval('time', function() { return; }, 10000)
4.0632 microseconds per iteration
js>
```

**Comment by dbohdan** [comment]
Looks good. A few comments:
* Switching on the `Tcl_ZlibCRC32` of the return type string is clever.
* Much of the code in `CallMethod_Cmd` now duplicates a subset of the functionality in `Tclduk_JSToTcl`. In the future one can replace that code with a call to `Tclduk_JSToTcl`.
* There is ambiguity when talking about converting a JSON string to an object in the readme because of what "object" means in the JSON spec and JS itself.  I wondered whether the JSON string must be `{ ... }` or arbitrary JSON.  I've tried to clear it up.
* The return type `arraylist` sounds redundant, since a Tcl list naturally translates to a JavaScript array. It also reminds me of Java.  Is there a reason to call it that?  I think it's best to change it to just `array`.

I've pushed your new commits with edited messages plus my README.md edit and `arraylist` renaming to https://github.com/dbohdan/tcl-duktape/tree/rkeene-tcl-eval.  I am ready to merge it to master and close the PR.  Since you're working on the Tcl lambda functionality, I won't tag `v0.7.0` yet.

**Comment by dbohdan** [comment]
P.S.: You haven't replied to me about the renaming of `js{proc,method}` to `js-{proc,method}`.  I would like to hear your opinion as the most active user of I know of of tcl-duktape.

**Comment by rkeene** [comment]
I do like `js-proc` and `js-method` being consistent better.

I pulled in your changes and made a slight change to the README that I think is helpful in noting that the conversion is from Tcl Lists -> JavaScript arrays

**Comment by dbohdan** [comment]
Good catch. I intended to change "array" to "list" there.

Merged (b33ebc8e91f48ba7e9ab85ac42cc6601aa7ce53c..207623f4421188ce401cb4fbd46af478aeb51149).  Thanks for contributing this feature!

**Pull request closed without merging**
